name: iris-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - mlflow==3.7.0
    - scikit-learn==1.5.2
    - pandas==2.2.3
    - lakefs==0.10.0
    - boto3==1.35.77
