stages:
  train_supervised:
    cmd: >
      mlflow run . -e supervised
      -P data_path=${data.path}
      -P target_column=${supervised.target_column}
      -P test_size=${data.test_size}
      -P validation_size=${data.validation_size}
      -P random_state=${data.random_state}
      -P n_estimators=${supervised.model.n_estimators}
      -P max_depth=${supervised.model.max_depth}
      -P experiment_name=${mlflow.experiment_name}
      -P model_name=${mlflow.model_name}
    deps:
      - src/train.py
      - src/data_loaders/
      - src/utils.py
      - ${data.path}
    params:
      - data.path
      - data.test_size
      - data.validation_size
      - data.random_state
      - supervised.target_column
      # Model's hyperparameters
      - supervised.model.n_estimators
      - supervised.model.max_depth
      # - supervised.model.learning_rate
    outs:
      - models/model.pkl
    metrics:
      - metrics.json:
          cache: false

# =============================================================================
# NOTES FOR DATA SCIENTISTS
# =============================================================================
#
# 1. DEPENDENCIES (deps):
#    - Files/directories that this stage depends on
#    - DVC tracks changes to these
#    - Stage re-runs if dependencies change
#
# 2. PARAMETERS (params):
#    - Values from params.yaml
#    - Use ${section.key} syntax
#    - Stage re-runs if parameters change
#
# 3. OUTPUTS (outs):
#    - Files generated by this stage
#    - Cached by DVC
#    - Can be pushed to remote storage
#
# 4. METRICS (metrics):
#    - JSON files with metrics
#    - cache: false means always read from file
#    - Viewable with: dvc metrics show
#
# 5. PLOTS (plots):
#    - Image files for visualization
#    - Viewable with: dvc plots show
#
# 6. COMMAND (cmd):
#    - Shell command to run
#    - Can use multi-line with >
#    - Can use parameter substitution
#
# =============================================================================
# COMMON DVC COMMANDS
# =============================================================================
#
# dvc repro                          # Run pipeline
# dvc repro train                    # Run specific stage
# dvc dag                            # Show pipeline DAG
# dvc status                         # Check for changes
# dvc metrics show                   # Show all metrics
# dvc metrics diff                   # Compare metrics across commits
# dvc params diff                    # Compare parameters across commits
# dvc plots show                     # Show plots
# dvc exp run                        # Run as experiment
# dvc exp show                       # Show all experiments
# dvc push                           # Push data to remote
# dvc pull                           # Pull data from remote
