stages:
  train_supervised:
    cmd: >
      python training/train.py --data-path ${data.path} --target-column ${supervised.target_column} --experiment-name ${mlflow.experiment_name} --model-name ${mlflow.model_name} --n-estimators ${supervised.model.n_estimators} --max-depth ${supervised.model.max_depth} --test-size ${data.test_size} --validation-size ${data.validation_size} --random-state ${data.random_state}
    deps:
    - training/train.py
    - src/data_loaders/
    - ${data.path}
    params:
    - data.path
    - data.test_size
    - data.validation_size
    - data.random_state
    - supervised.target_column
    - supervised.model.n_estimators
    - supervised.model.max_depth
    - mlflow.experiment_name
    - mlflow.model_name
    metrics:
    - metrics.json:
        cache: false
