# =============================================================================
# DATA CONFIGURATION
# =============================================================================
data:
  path: "data/processed/dataset.csv"  # Generic name
  test_size: 0.2
  validation_size: 0.1
  random_state: 42

# =============================================================================
# SUPERVISED LEARNING
# =============================================================================
supervised:
  target_column: "target"  # Generic target
  model:
    type: "random_forest"
    n_estimators: 100
    max_depth: 10

# =============================================================================
# MLFLOW CONFIGURATION
# =============================================================================
mlflow:
  experiment_name: "template-experiment"
  model_name: "template-model"
  tracking_uri: "http://localhost:5001"
