"""
Generate CML-compatible markdown report from model comparison.
Simple conversion from JSON to markdown for GitLab MR comments.
"""
import argparse
import json
from pathlib import Path


def generate_markdown_report(comparison: dict) -> str:
    """
    Generate markdown report from comparison JSON.
    Designed for CML (Continuous Machine Learning) comments.
    """
    
    promote = comparison.get("promote_challenger", False)
    comp = comparison.get("comparison", {})
    
    # Header with decision
    if promote:
        header = "# 🏆 Model Promoted to Champion\n\n"
        status_badge = "![Status](https://img.shields.io/badge/Status-PROMOTED-success)"
    else:
        header = "# ⚠️ Champion Retained\n\n"
        status_badge = "![Status](https://img.shields.io/badge/Status-RETAINED-yellow)"
    
    lines = [
        header,
        status_badge,
        "",
        "## 📊 Decision Summary",
        "",
        f"**Reason:** {comp.get('reason', 'No reason provided')}",
        "",
    ]
    
    # Metrics comparison table
    metric = comp.get("metric", "metric")
    champ_score = comp.get("champion_score")
    chall_score = comp.get("challenger_score")
    improvement = comp.get("pct_improvement", 0)
    
    lines.extend([
        "## 📈 Performance Comparison",
        "",
        f"**Primary Metric:** `{metric}`",
        "",
        "| Model | Score | Change |",
        "|-------|-------|--------|",
    ])
    
    # Champion row
    if champ_score is not None:
        lines.append(f"| Champion | `{champ_score:.4f}` | baseline |")
    else:
        lines.append("| Champion | N/A | _(first model)_ |")
    
    # Challenger row
    if chall_score is not None:
        change_emoji = "📈" if improvement > 0 else "📉" if improvement < 0 else "➡️"
        change_str = f"`{improvement*100:+.2f}%` {change_emoji}"
        lines.append(f"| **Challenger** | `{chall_score:.4f}` | {change_str} |")
    
    lines.append("")
    
    # All metrics (if available)
    all_metrics = comparison.get("all_challenger_metrics", {})
    if all_metrics and len(all_metrics) > 1:
        lines.extend([
            "<details>",
            "<summary><b>📋 All Metrics</b> (click to expand)</summary>",
            "",
            "| Metric | Value |",
            "|--------|-------|",
        ])
        
        for name, value in sorted(all_metrics.items()):
            # Highlight primary metric
            if name == metric:
                lines.append(f"| **{name}** | **`{value:.4f}`** |")
            else:
                lines.append(f"| {name} | `{value:.4f}` |")
        
        lines.extend(["", "</details>", ""])
    
    # Run IDs
    lines.extend([
        "---",
        "",
        "**Run Information:**",
        f"- Champion: `{comparison.get('champion_run_id', 'None')}`",
        f"- Challenger: `{comparison.get('challenger_run_id', 'Unknown')}`",
        "",
        f"_Generated by MLOps Pipeline_",
    ])
    
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate CML markdown report from comparison JSON"
    )
    parser.add_argument(
        "--comparison",
        required=True,
        help="Path to comparison.json"
    )
    parser.add_argument(
        "--output",
        default="report.md",
        help="Output markdown file"
    )
    
    args = parser.parse_args()
    
    # Load comparison
    comparison_path = Path(args.comparison)
    if not comparison_path.exists():
        print(f"❌ Comparison file not found: {comparison_path}")
        return 1
    
    with open(comparison_path) as f:
        comparison = json.load(f)
    
    # Generate report
    report = generate_markdown_report(comparison)
    
    # Save
    output_path = Path(args.output)
    with open(output_path, "w") as f:
        f.write(report)
    
    print(f"✅ CML report saved to {output_path}")
    
    # Preview (useful for debugging)
    print("\n" + "=" * 70)
    print("REPORT PREVIEW:")
    print("=" * 70)
    print(report)
    print("=" * 70)
    
    return 0


if __name__ == "__main__":
    exit(main())
